### ISSUE TITLE
Url Doramasyt

### ISSUE THREAD

**Issue by jasshira266** [Kohi-den/extensions-source#1]
### Source information

Doramasyt 14.13

### Source language

Spanish

### Source new URL

https://www.doramasyt.com/

### Other details

Before the url was added without www, now as the page has modified its website, they now have the www 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
This has no influence on the extension xD, The problem is that they have modified the page code 🤙
