### ISSUE TITLE
[BUG] SupJav - Infinitely repeating search result 

### ISSUE THREAD

**Issue by 0Ha16wA5** [Kohi-den/extensions-source#111]
### Source information

SupJav 14.9 (Multi)

### Source language

All

### Steps to reproduce

1. Search with any keywords
2. Results began to show
3. If the result is more than 24, it will get infinitely repeated.

### Expected behavior

The result is the same as the web

Example:
`reincarnation` on web -> 12 results
`reincarnation` with aniyomi extension -> 12 results
`stars` on web -> 1660 results
`stars` on aniyomi extension -> 1660 results

### Actual behavior

If the result is more than 24, it will get infinitely repeated.

Example:
`reincarnation` on web -> 12 results
`reincarnation` with aniyomi extension -> 12 results
`stars` on web -> 1660 results
`stars` on aniyomi extension -> infinitely repeating the first 24 results

### Aniyomi version

Aniyomi Stable 0.16.4.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
it's working now
