### ISSUE TITLE
Anitube 403 error

### ISSUE THREAD

**Issue by Kashynku** [Kohi-den/extensions-source#141]
### Source information

anitube-v14.14 (pt) 

### Source language

Portuguese Brazil

### Steps to reproduce

First Step (Open a random anime episode)
Second Step (Try to see a episode)
Third Step (error 403 forbidden occurs) 

![Screenshot_20240814-221724](https://github.com/user-attachments/assets/349830d6-265e-4a1a-9d95-e0fdec2d3a2b)

### Expected behavior

What should happen: The episode play normally

### Actual behavior

What happen instead: Error 403 Forbidden occurs

### Aniyomi version

0.16.4.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Possible reasons for this error:

The selected source has Cloudflare protection. Check the Cloudflare guide for solutions.

The source might be down, removed the series, or banned your IP.

Open WebView to confirm.

**Comment by Kashynku** [comment]
> Possible reasons for this error:
> 
> The selected source has Cloudflare protection. Check the Cloudflare guide for solutions.
> Already tried the open the webview from app and I can acess the sites and episodes normally

> The source might be down, removed the series, or banned your IP.

> Can acess the site and eps normally, tried asking a friend to test on his phone and the same problem occurs on aniyomi. I already tried to change the Agent, no sucess. 


> Open WebView to confirm.
![Screenshot_20240815-110943](https://github.com/user-attachments/assets/8b9c82b6-3951-4c3c-a81a-967e148f0df4)
![Picsart_24-08-15_11-18-18-817](https://github.com/user-attachments/assets/a9a64206-75e6-4a60-8a4c-73b4459e35e4)

**Comment by WebDitto** [comment]
I am working on it, I will write a solution on this weekend

**Comment by paz-web** [comment]
Continua sem funcionar
