### ISSUE TITLE
AnimeID is not working

### ISSUE THREAD

**Issue by Latinlee** [Kohi-den/extensions-source#142]
### Source information

AnimeID 14.8 (spanish)

### Source language

Spanish

### Steps to reproduce

1. Open AnimeId
2. Play any anime chapter

### Expected behavior

Should play any chapter

### Actual behavior

The player closes and show the message "video list is empty"

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Other details

It seems that servers are missing
![IMG_20240815_071542](https://github.com/user-attachments/assets/85a01791-ffae-4288-b1c3-de7414b67802)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
This has already been fixed and it works

**Comment by WebDitto** [comment]
Thanks @Dark25

**Comment by Latinlee** [comment]
Excuse my ignorance, should I wait for the update to be released for this extension? @Dark25 said it was already fixed but now it continues to give the same error.

**Comment by Dark25** [comment]
> Excuse my ignorance, should I wait for the update to be released for this extension? @Dark25 said it was already fixed but now it continues to give the same error.

Have you updated the extension recently?

**Comment by Latinlee** [comment]
> > Excuse my ignorance, should I wait for the update to be released for this extension? @Dark25 said it was already fixed but now it continues to give the same error.
> 
> Have you updated the extension recently?

Not yet, it's the same version
