### ISSUE TITLE
Vidstream and MegaF servers do not work on Aniwave 

### ISSUE THREAD

**Issue by Wafffle23** [Kohi-den/extensions-source#145]
### Source information

Aniwave 14.74 (English)

### Source language

English

### Steps to reproduce

1. Try to watch some anime with "softsub" For example: Black clover chapter 1
2. Search the player for the vidstream and MegaF servers that contain the "softsub"
3. The servers do not appear, only MoonF and Mp4Upload

### Expected behavior

The other servers already mentioned (vidstream and MegaF) should appear, however, only MoonF and Mp4Upload appear. It should appear like on the aniwave website. 
![Screenshot_20240815_132714_com brave browser](https://github.com/user-attachments/assets/0f9ae8bd-cf5a-4f2c-a0dd-cb6fd85fa981)

### Actual behavior

However, the other servers do not appear. This is what the Aniyomi player shows
![Screenshot_20240815_132429_xyz jmir tachiyomi mi](https://github.com/user-attachments/assets/d97e7866-f696-4786-9a1e-cee760bd9fc4)

### Aniyomi version

0.16.4.3

### Android version

Android 10

### Other details

Huawei P40 Lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by JudgeDreddpool** [comment]
Wanted to note that I'm still experiencing this error. Hoping that it'll be fixed soon.

**Comment by almightyhak** [comment]
Rip to aniwave
