### ISSUE TITLE
Add new source 'anix.to'

### ISSUE THREAD

**Issue by NichirinSword** [Kohi-den/extensions-source#146]
### Source name

Anix

### Source link

https://www.anix.to/home

### Source language

English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/Kohi-den/extensions-source) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Domain down
