### ISSUE TITLE
Kaido doesn’t loading any stream source 

### ISSUE THREAD

**Issue by NichirinSword** [Kohi-den/extensions-source#147]
### Source information

Kaido v14.9

### Source language

English

### Steps to reproduce

Try to watch any episode from any anime, it shows no stream available.

### Expected behavior

When selecting it should show the available stream to watch

### Actual behavior

No stream available 

### Aniyomi version

Dantotsu v3.1.0-alpha01

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
it's works fine
