### ISSUE TITLE
HiAnime doesn't work with raw episodes

### ISSUE THREAD

**Issue by deltakiro** [Kohi-den/extensions-source#152]
### Source information

HiAnime 14.43

### Source language

English

### Steps to reproduce

Step 1: Open aniyomi.
Step 2: Search any new anime episode added on HiAnime. (Sush as That time I got reincarnated as a Slime season 3)
Step 3: Try watching the latest episode. 

### Expected behavior

Should have opened the episode in the player but doesn't cause the episode is as a RAW on the actual website.

### Actual behavior

Gives me the "Video list is empty message" and does not open the player.

### Aniyomi version

Preview r7801

### Android version

Android 14

### Other details

1. Samsung OneUI 6.1
2. Android Webview up-to-date 
3. Tried in the stable release too but doesnt work.
Here are the images:
[
![Screenshot_20240817_135144_Aniyomi](https://github.com/user-attachments/assets/41e45ff7-1602-4b67-9713-122b2b2f747c)

![Screenshot_20240817_142540_Samsung Internet](https://github.com/user-attachments/assets/5bdd80a5-20d9-43d1-bc6a-0df0bc7ca879)

![Screenshot_20240817_141613_Samsung Internet](https://github.com/user-attachments/assets/8d10ba2f-1a38-4c73-877b-e76a8272c3b8)
](url)

Maybe just adding that raw thing will work as some old anime on this website are raw too
![Screenshot_20240817_142419_Aniyomi](https://github.com/user-attachments/assets/f68f7329-ebee-47d9-a291-041db693f9ca)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
the extension is ok
