### ISSUE TITLE
Subsplease is disabled

### ISSUE THREAD

**Issue by apcallh** [Kohi-den/extensions-source#161]
### Source name

Subsplease

### Source language

English

### Source link

https://subsplease.org/

### Other details

Hello, the "Subsplease" add-on does not work. I hope there is a solution or if it is possible to change its source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Duplicate, closed in favor of #160 why did you make 2 issues?
