### ISSUE TITLE
Oppai Stream Ext. Broken

### ISSUE THREAD

**Issue by SwiftGrim** [Kohi-den/extensions-source#166]
### Source information

Oppai Stream 14.4 (English)

### Source language

English 

### Steps to reproduce

1. Open any content from the ext.
2. Try to watch it
3. NullPointerException: null

### Expected behavior

Usually you wat have watch it without issues 

### Actual behavior

But unstead I got "NullPointerException: null"

### Aniyomi version

 0.16.4.3 

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
close  is ok
