### ISSUE TITLE
Better anime

### ISSUE THREAD

**Issue by paz-web** [Kohi-den/extensions-source#171]
### Source information

Better anime 14.11

### Source language

PT BR 

### Steps to reproduce

Quando você aperta para baixar o episódio pelo ADM ele abaixa uma outra coisa mais não o episódio

### Expected behavior

Baixar normalmente o episódio 

### Actual behavior

Baixa somente a foto do episódio 

### Aniyomi version

0.16.4.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by WebDitto** [comment]
@paz-web , I did some tests here and is working like a charm, could you provide the anime name to test here?

**Comment by paz-web** [comment]
> @paz-web, Fiz alguns testes aqui e está funcionando perfeitamente. Você poderia fornecer o nome do anime para testar aqui?

Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu - Dublado
![Screenshot_20240827-201550](https://github.com/user-attachments/assets/68012095-0144-4abf-b580-3fa3279fcb3e)

**Comment by WebDitto** [comment]
I tested here, and is working normally.

The printscreen that you sended is not from extension
