### ISSUE TITLE
Add Porn Sites

### ISSUE THREAD

**Issue by rajinstar** [Kohi-den/extensions-source#172]
### Source name

Pornhub, Xvideos and Xnxx

### Source link

"www.pornhub.com", "www.xvideos.com", "www.xnxx.com"

### Source language

English 

### Other details

18+/NSFW = yes 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/Kohi-den/extensions-source) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Delmarcop52** [comment]
Dude are you alright

**Comment by kyoyacchi** [comment]
💀
