### ISSUE TITLE
Genoanime extension is not working

### ISSUE THREAD

**Issue by rajinstar** [Kohi-den/extensions-source#173]
### Source name

Genoanime

### Source language

English 

### Source link

https://genoanime.com/

### Other details

![Screenshot_2024-08-23-16-53-20-937_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/430169d3-08ea-4160-83f8-8aa0103de5bc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
close is ok
