### ISSUE TITLE
Aniwave Extension Update problem (Ask to update every time the same version after update)

### ISSUE THREAD

**Issue by rajinstar** [Kohi-den/extensions-source#174]
### Source information

Aniwave 14.73 (English)

### Source language

English

### Steps to reproduce

First step: Open Aniyomi, second step: go to Browse, third step: go to Anime extension forth step: install Aniwave, fifth step: ask to update the extension (same version of before install the extension), and final step: ask every time to update the same version of this extension.

### Expected behavior

After updated, it should be updated and not again asking for an update.

### Actual behavior

I update it several time until now. I will explain it to you. First I update Aniwave in Aniyomi. But, When I restart the app or close the app and again open the app or when I refresh the Anime Extension option then Aniwave ask me to update the same version everything. I don't remember how many time I was update this extension. But, everything it ask me to update the extension of the same version.

### Aniyomi version

0.16.4.3-7801

### Android version

Android 12

### Other details

![Screenshot_2024-08-23-16-54-38-187_xyz jmir tachiyomi mi debug](https://github.com/user-attachments/assets/e02f3a09-9062-4833-b1b1-2eeb08fa3829)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Reinstall it

**Comment by rajinstar** [comment]
> Reinstall it

I done it several times but same problem.

**Comment by almightyhak** [comment]
Are you perhaps on a Samsung?

**Comment by rajinstar** [comment]
> Are you perhaps on a Samsung?

No, POCO M2 Pro

**Comment by almightyhak** [comment]
Uninstall it and download it from [here](https://github.com/Kohi-den/extensions/blob/main/apk/aniyomi-en.nineanime-v14.75.apk)
