### ISSUE TITLE
Aniwave 

### ISSUE THREAD

**Issue by Delmarcop52** [Kohi-den/extensions-source#191]
### Source name

aniwave.to

### Source language

English

### Source link

https://aniwave.to/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
... Did you even check the website you're suggesting

**Comment by Delmarcop52** [comment]
I was trying to remove this extension
