### ISSUE TITLE
Superstream

### ISSUE THREAD

**Issue by ILSN1996** [Kohi-den/extensions-source#196]
### Source information

Superstream

### Source language

English 

### Source new URL

www.showbox.media/

### Other details

Hello, superstream extension is broken for a long time and website changed to showbox.media. so please fix it, thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Duplicate, closed in favor of #103
