### ISSUE TITLE
SuperStream : url change

### ISSUE THREAD

**Issue by OtakuArab** [Kohi-den/extensions-source#198]
### Source information

Superstream 14.11

### Source language

English

### Source new URL

https://www.showbox.media

### Other details

We hope to solve the source problemWe hope to solve the source problem 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Duplicate, closed in favor of #103

**Comment by OtakuArab** [comment]
> Duplicate, closed in favor of #103

#103 
The link is old and no longer works
