### ISSUE TITLE
Torrentio doesn't load videos

### ISSUE THREAD

**Issue by JudgeDreddpool** [Kohi-den/extensions-source#218]
### Source information

Torrentio 14.1 (Multi)

### Source language

Multi

### Steps to reproduce

1. Open any movie or TV show in Torrentio
2. Play the movie or an episode from the TV show

### Expected behavior

The movie or episode should play like normal.

### Actual behavior

Video doesn't load and instead get greeted with "loading failed" error
![Screenshot_20240906-161601_Aniyomi](https://github.com/user-attachments/assets/1f4329b9-8007-44f5-a46a-c6dcf3a288cc)

### Aniyomi version

Preview 7809

### Android version

Android 9

### Other details

This only applies to Torrentio and not Torrentio Anime, though I'm unsure if the same error affects Torrentio Anime.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Check #219

**Comment by JudgeDreddpool** [comment]
I'm a little confused. What am I meant to do, because this isn't for the Anime version of Torrentio, but the non-Anime version.
