### ISSUE TITLE
Episode list doesn't load in Torrentio Anime

### ISSUE THREAD

**Issue by KryptoSynth** [Kohi-den/extensions-source#219]
### Source information

Torrentio Anime 14.8

### Source language

Multi

### Steps to reproduce

1. Go to Browse tab.
2. Install and open Torrentio Anime source.
3. Click on an Anime.

### Expected behavior

The episodes for the anime should load.

### Actual behavior

They don't load and I get an error.

### Aniyomi version

0.16.4.3

### Android version

Android 13

### Other details

This behavior doesn't occur with anime in my library where the episodes already loaded (added with older versions of Torrentio.)

[aniyomi_crash_logs.txt](https://github.com/user-attachments/files/16912337/aniyomi_crash_logs.txt)

The errors are the same in Kuukiyomi 0.3.2.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LAST-pie** [comment]
Working perfectly 
![Screenshot_20240909-000408_Kuukiyomi](https://github.com/user-attachments/assets/e92c7afe-2304-4f22-8eb8-bccac4a17878)

**Comment by KryptoSynth** [comment]
@LAST-pie  Thanks I figured it out! 

The extension needs to contact api.ani.zip. I use NextDNS and it was set to block .zip domains by default. I'm gonna change that now.
