### ISSUE TITLE
Animes saved in library not marked "in library"

### ISSUE THREAD

**Issue by MonomoySama** [Kohi-den/extensions-source#221]
### Source information

Hianime 14.43

### Source language

English 

### Steps to reproduce

Try migrating any anime from other ext to hianime and check if that anime is "in library" marked in hianime (i did it from Aniplay to Hianime)

### Expected behavior

it should be like the last one i showed in the video which is marked "in library", and that's marked cause i didn't migrated it, i opened the hianime ext and straight added it to library from there, that's why it's "in library" marked

### Actual behavior

Shown in video

### Aniyomi version

0.16.4.3

### Android version

Android 10

### Other details

Even though it's not a major problem, but i have check if a anime is already in my library or not everytime, if it's not fixed

This is the video link - https://drive.google.com/file/d/14pOdlABNoVT39DaAd9gM4XUOR-2hBZze/view?usp=drivesdk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
seems like a problem with aniyomi itself, go make an issue on their repo
