### ISSUE TITLE
HiAnime Video list empty

### ISSUE THREAD

**Issue by Curiousnewbie** [Kohi-den/extensions-source#223]
### Source information

HiAnime 14.43

### Source language

English/Japanese

### Steps to reproduce

1. Open HiAnime 
2. Search One Peice
3. Try to open an episode

### Expected behavior

The selected episode should play

### Actual behavior

Its showing a toast saying "Video list is empty"
![Screenshot_2024-09-09-23-01-07-434_xyz jmir tachiyomi mi debug-edit](https://github.com/user-attachments/assets/dbef8878-59d4-49e4-b064-f02cb33cd8d2)

### Aniyomi version

Preview r7809

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by imper1aldev** [comment]
This extension works correctly, what happens is that you have tried to play an episode that doesn't exist yet, in fact in your screenshot it specifically says “Airing in 5 DAYS....”.

fyi @almightyhak
