### ISSUE TITLE
HTTP error 404 Not Found

### ISSUE THREAD

**Issue by FateJapan** [Kohi-den/extensions-source#225]
### Source information

AnimesROLL 14.4

### Source language

Português (Brasil)

### Source new URL

https://www.anroll.net/

### Other details

It's been about two weeks since this problem started appearing: HTTP error 404 Not Found.

When you access the WebView option, the URL is working normally.

This error is only happening with new episodes that are being added recently.

PS: Any other episode prior to these two weeks that started showing this error, works normally.

![01](https://github.com/user-attachments/assets/a4b0e91b-1284-4a6f-badb-d1911d682a1c)
![02](https://github.com/user-attachments/assets/dca2e51f-21a7-492e-be7b-35422a0a46cd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by WebDitto** [comment]
Now they have two CDN for the content, the old `https://cdn-02.gamabunta.xyz` and the new `https://cdn-zenitsu-2-gamabunta.b-cdn.net`, the server is based on `se_pgad` in the response

**Comment by FateJapan** [comment]
> Now they have two CDN for the content, the old `https://cdn-02.gamabunta.xyz` and the new `https://cdn-zenitsu-2-gamabunta.b-cdn.net`, the server is based on `se_pgad` in the response

And what does that mean? Sorry, but I don't understand anything about the subject.

**Comment by FateJapan** [comment]
Thanks for fixing the issue, it's working now.
I would also like to let you know that the external video player is no longer working, only the native video player.

![15017](https://github.com/user-attachments/assets/bad54b9b-5782-4fa6-bbb7-df8830fac945)
