### ISSUE TITLE
Add AniTora Source (PT-BR)

### ISSUE THREAD

**Issue by FateJapan** [Kohi-den/extensions-source#226]
### Source name

AniTora

### Source link

https://anitora.ru/

### Source language

Português (Brasil)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/Kohi-den/extensions-source) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by WebDitto** [comment]
I have the base code to work with this source, but the m3u8 files has a image header that broke it.

We need to find something like `skip_initial_bytes=25` of FFMPEG to work with this.

**Comment by FateJapan** [comment]
> I have the base code to work with this source, but the m3u8 files has a image header that broke it.
> 
> We need to find something like `skip_initial_bytes=25` of FFMPEG to work with this.

Ok, no problem. Too bad I don't understand anything about it.

**Comment by WebDitto** [comment]
This source is down
