### ISSUE TITLE
Torrentio and Torrentio Anime doesn't load videos

### ISSUE THREAD

**Issue by JudgeDreddpool** [Kohi-den/extensions-source#231]
### Source information

Torrentio 14.1 (Multi) & Torrentio Anime 14.8 (Multi)

### Source language

Multi

### Steps to reproduce

1. Open any movie/TV show/anime
2. Play the movie or an episode from the TV show/anime

### Expected behavior

The movie or episode should play normally.

### Actual behavior

Instead, I get greeted with the video player giving me a "loading failed" error and nothing but a black screen.
![Screenshot_20240912-042226_Aniyomi](https://github.com/user-attachments/assets/60facbea-6b05-499b-900c-d8314aa79692)

### Aniyomi version

Preview r7809

### Android version

Android 9

### Other details

Yes, I know this was an issue that was seemingly resolved, but I should clarify that this is absolutely NOT the same issue as #219. The episode lists load fine, but the videos themselves will not play. That is the error I'm getting here.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LAST-pie** [comment]
Don't know why yall be complaining about torrentio, it working very fine like always do
![Screenshot_20240913-215659_Kuukiyomi](https://github.com/user-attachments/assets/2178543b-025c-43e3-b567-e7cd76d99dcb)

**Comment by JudgeDreddpool** [comment]
Well, that's great it's working for you. But I can't get it working at all.

**Comment by almightyhak** [comment]
What app are you using? Aniyomi? Kuukiyomi?

**Comment by JudgeDreddpool** [comment]
Answered on the Discord already, but I'm using Aniyomi... which apparently doesn't support torrents presently.

Feel free to close this, since I now know the reason for the extensions not working on my end is due to the app lacking the ability to support torrents.
