### ISSUE TITLE
luciferdonghua.in is shutting down soon and starts a new site called  misterdonghua.com

### ISSUE THREAD

**Issue by rybuilder23** [Kohi-den/extensions-source#248]
### Source information

aniyomi-en.luciferdonghua-v14.6.apk

### Source language

English

### Source new URL

https://misterdonghua.com/

### Other details

luciferdonghua.in is shutting down and starts  a new site called
misterdonghua.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by Neplo0908A** [comment]
They already shut it down

**Comment by Dark25** [comment]
The domain link works correctly
