### ISSUE TITLE
Otakudesu Can't stream 

### ISSUE THREAD

**Issue by kitsu2** [Kohi-den/extensions-source#252]
### Source information

Otakudesu 14.26

### Source language

Indonesia 

### Steps to reproduce

1.Select anime from otakudesu extension 
2.And select the episode it shows no streaming found 

### Expected behavior

Can watch anime 

### Actual behavior

Shows no streaming 

### Which app are you using?

Dantotsu 

### App version

3.1.0

### Android version

Android 14

### Other details

Can It Be Fixed Soon 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by itsmechinmoy** [comment]
Did u check if it works in Aniyomi or not?

**Comment by kitsu2** [comment]
> Did u check if it works in Aniyomi or not? If it's working in aniyomi then probably the issue is with dantotsu and u need to create a bug report in their discord server

Yes I tried the extension in aniyomi and it shows the same thing
