### ISSUE TITLE
Add source: 朋友韓漫 / pengyouhanman

### ISSUE THREAD

**Issue by RejectVanity** [Kohi-den/extensions-source#254]
### Source name

朋友韓漫（pengyouhanman）

### Source link

https://www.pengyouhanman.com

### Source language

Chinese

### Other details

18+/NSFW = yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/Kohi-den/extensions-source) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Sorry but this repo is for video extensions only

**Comment by RejectVanity** [comment]
> Sorry but this repo is for video extensions only

Thank you for your tolerance, understanding, and guidance.
