### ISSUE TITLE
Superstream extension url 

### ISSUE THREAD

**Issue by ILSN1996** [Kohi-den/extensions-source#260]
### Source information

Superstream 14.11

### Source language

English 

### Source new URL

https://www.showbox.media/

### Other details

Extension broken please fix it, the actual url is https://www.showbox.media/
Thanks 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
dupe closed in favor of #103
