### ISSUE TITLE
Showbox

### ISSUE THREAD

**Issue by Combomain** [Kohi-den/extensions-source#269]
### Source name

Www.showbox.media

### Source link

https://www.showbox.media/movie?genre=10

### Source language

English 

### Other details

+18

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/Kohi-den/extensions-source) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Duplicate #103
