### ISSUE TITLE
Fmovies URL change 

### ISSUE THREAD

**Issue by Lance99970** [Kohi-den/extensions-source#274]
### Source information

https://fmovies24.to/

### Source language

English 

### Source new URL

https://ww4.fmovies.co/24/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by david79111** [comment]
https://fmoviesz24.net/ also works
