### ISSUE TITLE
Tokuzilla timeout error

### ISSUE THREAD

**Issue by JudgeDreddpool** [Kohi-den/extensions-source#280]
### Source information

Tokuzilla 14.17 (English)

### Source language

English

### Steps to reproduce

1. Open a TV show or movie (example: Kamen Rider Kuuga)
2. Play an episode from the show or the movie

### Expected behavior

The episode or movie should play like normal.

### Actual behavior

Instead, the player loads for a bit, before booting me back to the menu with a "timeout" error.
![image](https://github.com/user-attachments/assets/b405cb32-6a46-436b-af8d-891e1a2ffb99)

### Which app are you using?

Aniyomi

### App version

Preview r7814

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Hello, have you updated the extension to the latest version?

**Comment by Dark25** [comment]
is ok for me 
![image](https://github.com/user-attachments/assets/62a521fb-d572-45ff-a782-937b6af62a5a)

**Comment by JudgeDreddpool** [comment]
> Hello, have you updated the extension to the latest version?

I legit am using the latest version of the extension, and yet I still get this error.

**Comment by JudgeDreddpool** [comment]
Also to note, I've tried changing my User Agent String and even tried to watch without my Wifi enabled on the app, but have still had no luck.

**Comment by JudgeDreddpool** [comment]
New update fixed this. Video player works now. You're free to close this.
