### ISSUE TITLE
Yo movies extension not working 

### ISSUE THREAD

**Issue by Jashanbhakar** [Kohi-den/extensions-source#283]
### Source name

Yo movies 

### Source language

English 

### Source link

https://yomovies.onl/

### Other details

All the movies and series in extension are notgetting updated and nothing is playing on the extension and if we go and see website through web view it is showing webpage not available. 

![Screenshot_20241002-002724](https://github.com/user-attachments/assets/5ff75ad7-3d6b-4cd5-a443-409a36f82191)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source website is down.
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
web page is ok

**Comment by Jashanbhakar** [comment]
No it is not it is not working

**Comment by Jashanbhakar** [comment]
Did you even check it was working or not

**Comment by Jashanbhakar** [comment]
> web page is ok

No it is not working I gave you the link of main website that is working but when I open the website via extension then it doesn't open so please the access link

**Comment by Jashanbhakar** [comment]
> > web page is ok
> 
> No it is not working I gave you the link of main website that is working but when I open the website via extension then it doesn't open so please the access link

The link that I have given in source link is the working one and the link of website
