### ISSUE TITLE
The gogoanime extension doesnt work anymore

### ISSUE THREAD

**Issue by Almighty-Finger** [Kohi-den/extensions-source#286]
### Source information

anitaku.to

### Source language

English

### Source new URL

anitaku.pe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by LAST-pie** [comment]
It IS working 
![Screenshot_20241006-020134_Kuukiyomi](https://github.com/user-attachments/assets/4af216cc-ce0e-4d87-ac3c-2674269c048a)
![Screenshot_20241006-020129_Kuukiyomi](https://github.com/user-attachments/assets/37995dc3-b718-4b41-9a7e-554fb6be327f)

**Comment by almightyhak** [comment]
I don't see any error messages so I'll close it for now
