### ISSUE TITLE
AniTube again

### ISSUE THREAD

**Issue by paz-web** [Kohi-den/extensions-source#289]
### Source information

AniTube 14.19 (Brasil)

### Source language

PT BR 

### Steps to reproduce

1: entrar na extensão 2 apertar em qualquer vídeo 3 não abre nenhum vídeo 

### Expected behavior

Abrir o episódio normalmente 

### Actual behavior

![Screenshot_20241005-203707](https://github.com/user-attachments/assets/d7a5c4f4-a5e0-4e0c-a276-eddba29308c2)

### Which app are you using?

Aniyomi

### App version

App version: 0.16.4.3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by Olintopinto** [comment]
Para mim funciona perfeitamente

**Comment by WebDitto** [comment]
Parte do problema é o próprio AniTube, que para vídeos mais antigos, por volta de 2016 e anteriores, não carrega nem no site oficial.

Eu tinha colocado um código para tentar buscar pelo link de download, mas eles mudaram novamente e colocaram uma proteção forte via CloudFlare.

Estou ajustando as extensões PT-BR quando tenho oportunidade.
