### ISSUE TITLE
Add support for "RAW" Episodes to HiAnime Extension

### ISSUE THREAD

**Issue by Aaaboy97** [Kohi-den/extensions-source#293]
### Source name

HiAnime

### Source language

English

### Describe your suggested feature

Add support for episodes classified as Raw in addition to the current support for Sub and Dub episodes to the HiAnime extension.

### Other details

Some new episodes on HiAnime are occasionally flagged on the website as "Raw" instead of "Sub" despite still having subtitles. The extension is unable to play these episodes, as it only has options for "Sub", "Dub", or "Mixed."

When an episode on the website has Raw and Dub available, the extension only plays the Dub. If Dubbed episodes are disabled in the Enabled/Disabled Types, or there's only the raw episode available, the episode will not play at all, and show "Empty Video List"

This has previously been raised as a bug, but it seems the extension is working as intended, and just only supports episodes labelled sub and dub, not raw.

![Screenshot_20241007-051218](https://github.com/user-attachments/assets/d51ffb3a-a12c-4ab0-b289-65f196f77ca9)
![Screenshot_20241007-051254](https://github.com/user-attachments/assets/402c8097-96b3-41d8-bbdc-ef872065f80a)
![Screenshot_20241007-051312](https://github.com/user-attachments/assets/386ec467-3bb7-498f-b9d6-d257df7f97d8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
Exactly in which chapter does this happen to you?

**Comment by Aaaboy97** [comment]
> Exactly in which chapter does this happen to you?

The issue happens with only newly released episodes. Any episode that shows "RAW" in the web view instead of "SUB" or "DUB". After a couple days, the episode is updated on the website to be "SUB". You can usually identify episodes by using the "Recently Updated" page from the website.

A specific example of an episode that is RAW at the time of this comment (although it may be updated to SUB later) is "Houkago Shounen Hanako-kun Part 2" Episode 1
