### ISSUE TITLE
Aniplay keep saying that video empty 

### ISSUE THREAD

**Issue by Delmarcop52** [Kohi-den/extensions-source#312]
### Source information

Aniplay 14.7

### Source language

English

### Steps to reproduce

1.open the app
2.search dragon ball kai
3.try to watch 

### Expected behavior

The extension is working 

### Actual behavior

The video is not empty 

### Which app are you using?

Aniyomi 

### App version

App version: 0.16.4.3-7814 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
I tested it and it's working fine
