### ISSUE TITLE
(bug) aniplay.lol saying that video is empty 

### ISSUE THREAD

**Issue by Delmarcop52** [Kohi-den/extensions-source#316]
### Source information

Aniplay.lol 14.7

### Source language

English

### Steps to reproduce

1.open extension 
2.search dragon ball 
3.watch 

### Expected behavior

The video is working 

### Actual behavior

It's keeping saying that video is empty 

### Which app are you using?

Aniyomi 

### App version

App version: 0.16.4.3-7814 

### Android version

Motorola 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by Ridwan155-Akasake** [comment]
I was facing the same problem just now, this only mentioned dragon ball, im facing this problem with dragon ball super. But aniplay is working fine with other series'. Not sure about all, i only check a few from the latest filter.
Hope its fixed soon.

**Comment by JosefFStraka** [comment]
Issue can be closed.
