### ISSUE TITLE
Rine cloud episódios sem abrir 

### ISSUE THREAD

**Issue by paz-web** [Kohi-den/extensions-source#327]
### Source information

Rinecloud 14.12

### Source language

PR BR

### Steps to reproduce

Alguns episódios não abre e e não conseguir identificar um padrão 

### Expected behavior

Abrir episódio normalmente 

### Actual behavior

Não abre

### Which app are you using?

Aniyomi 

### App version

0.16.4.3

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by WebDitto** [comment]
Some new episodes are using a new internal source, I need to update the extractor to handle it.
They are using a direct link for a mp4 file instead of googlevideo or m3u8 list
