### ISSUE TITLE
Fmovies New URL

### ISSUE THREAD

**Issue by Ankit-Xt** [Kohi-den/extensions-source#330]
### Source information

Fmovies 14.25

### Source language

English 

### Source new URL

https://fmovies-hd.to/home/

### Other details

I know the orginal fmovies is down , and this one is a copy but still it has the same features and ui so why don't we use it ...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by david79111** [comment]
https://fmoviesz24.net/ also works
