### ISSUE TITLE
Aniplay: Failed to Bypass Cloidflare

### ISSUE THREAD

**Issue by C0untD0wn777** [Kohi-den/extensions-source#354]
### Source information

Aniplay 14.7 (English)

### Source language

English

### Steps to reproduce

Step 1: on Aniyomi, view "Anime Sources" in the Browse section.
Step 2: click on Aniplay.
Step 3: it shows the Cloudflare error immediately.

### Expected behavior

You should be able to click on Aniplay and view the anime listed.

### Actual behavior

Instead, it shows the "Failed to Bypass Cloudflare" error.

### Which app are you using?

Aniyomi

### App version

0.16.4.3

### Android version

Android 13

### Other details

![Screenshot_20241106_161800_Aniyomi](https://github.com/user-attachments/assets/8450d6a7-5785-4400-b412-64eab564acff)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by Delmarcop52** [comment]
It worked for me

**Comment by almightyhak** [comment]
Try Changing your user agent

Navigate to More -> Settings -> Advanced.
Modify Default user agent string to another value.
[Here's yours](https://www.whatismybrowser.com/detect/what-is-my-user-agent/) everyone have different user agents

Restart the app and retry.

**Comment by C0untD0wn777** [comment]
Thanks you guys, it works now. Appreciate it.
