### ISSUE TITLE
Fmovies url change

### ISSUE THREAD

**Issue by Sukidecat** [Kohi-den/extensions-source#391]
### Source information

Fmovies 14.25

### Source language

English 

### Source new URL

https://fmovies247.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by trout6516** [comment]
This site is quite different to the old sites. https://fmovies-hd.to/ is the fan site that is nearly identical.

**Comment by almightyhak** [comment]
The fmovies is dead this is a fake, if you want a new source then use the source request template, not the bug one
