### ISSUE TITLE
Aniwave new URL

### ISSUE THREAD

**Issue by C0untD0wn777** [Kohi-den/extensions-source#402]
### Source information

Aniwave 14.73 (English)

### Source language

English

### Source new URL

https://aniwave.se/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Aniwave is dead this is most likely a a fake
