### ISSUE TITLE
Gogoanime (Anitaku) new domain

### ISSUE THREAD

**Issue by C0untD0wn777** [Kohi-den/extensions-source#410]
### Source information

Gogoanime 14.84

### Source language

English

### Source new URL

https://anitaku.io/

### Other details

It has all the episodes. But it shows that the next episode aired when it hasn't yet (check Dandadan for example). 
![Screenshot_20241204_123816_Chrome](https://github.com/user-attachments/assets/69061e02-7fb7-4dec-be07-2aa21985bc6f)
![Screenshot_20241204_123810_Chrome](https://github.com/user-attachments/assets/6795ed93-a871-4fed-8282-73a69778f90a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by GregiPlays** [comment]
Anitaku.io is literally not a original domain from gogo

![image](https://github.com/user-attachments/assets/8f70789d-a3ae-4b05-972b-1906cefa8b69)

**Comment by C0untD0wn777** [comment]
Damn. But the link I provided has the original subs and updated episodes like the OG gogoanime had before it froze.

**Comment by GregiPlays** [comment]
This doesn't really matter, since it's not gogo and not one of their official domains.
