### ISSUE TITLE
Webtoon source is not working 

### ISSUE THREAD

**Issue by knightmob** [Kohi-den/extensions-source#415]
### Source information

Webtoon 1.4.41

### Source language

English 

### Steps to reproduce

If you click the source it just eternally loads and won't display catalogue, butif you webview it works and loads just fine.

### Expected behavior

The  source should display the homepage just like the webview

### Actual behavior

Instead it loads eternally 

### Which app are you using?

Mihon

### App version

Mihon 0.17.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
This is an anime repo not manga/manhwa/webtoons repo

**Comment by knightmob** [comment]
Sorry for the confusion
