### ISSUE TITLE
AnimeUnity Failed to fetch videos

### ISSUE THREAD

**Issue by benaversano98** [Kohi-den/extensions-source#54]
### Source information

AnimeUnity

### Source language

Italian

### Steps to reproduce

1. Open App
2. Select an episode from AnimeUnity

### Expected behavior

See the episode

### Actual behavior

Appear the error "Failed to fetch videos"

### Aniyomi version

Prewiew r7714

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dark25** [comment]
extension is ok
