### ISSUE TITLE
FMovies URL source change request 

### ISSUE THREAD

**Issue by RavenVan31** [Kohi-den/extensions-source#67]
### Source information

FMovies 

### Source language

Multi

### Source new URL

https://fmovie-s.to/

### Other details

URL source change request from the old FMovies site. The same site but better and improved info

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by MrD005** [comment]
Any update on this?
